# Generated by Django 3.1 on 2021-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Подробное описание задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Описание задачи'),
        ),
    ]
